spring.datasource.username=restadmin
spring.datasource.password=password
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/restdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration